### PR TITLE
Fix int vs uint serialization

### PR DESCRIPTION
**Pull request by zacpullen**
Hi Matthias,

Thanks for the great library, just had a little fix to allow negative numbers to be serialized. 

Cheers
Zac

### CODE REVIEW

**Comment by padcom** [comment]
Thanks @zacpullen. I missed that.

**Comment by padcom** [comment]
I'll release the package Tomorrow in the evening once I get back home. For the time being, you can use it straight from GitHub's master

**Comment by padcom** [comment]
1.0.2 released.

**Comment by gribbet** [comment]
Hey @padcom the 1.0.2 release on npm does not include this fix. It looks like dist needs to be rebuilt

**Comment by padcom** [comment]
@gribbet The fix is in the runtime part of the library - not the mappings. The mappings are pulled in from a separate package called mavlink-mappings. Those two are deployed separately. The runtime package, node-mavlink, only contains tools that use the mappings to do the actual job of serializing/deserializing messages which are otherwise just definitions of packets.

**Comment by gribbet** [comment]
Thanks @padcom but please clarify.

I am referring to the node-mavlink package here. The 1.0.2 version on npm (https://registry.npmjs.org/node-mavlink/-/node-mavlink-1.0.2.tgz) has this in `dist/lib/serialization.js`:

```
    'char': (value, buffer, offset) => buffer.writeUInt8(value, offset),
    'int8_t': (value, buffer, offset) => buffer.writeUInt8(value, offset),
    'uint8_t': (value, buffer, offset) => buffer.writeUInt8(value, offset),
    'int16_t': (value, buffer, offset) => buffer.writeUInt16LE(value, offset),
    'uint16_t': (value, buffer, offset) => buffer.writeUInt16LE(value, offset),
    'int32_t': (value, buffer, offset) => buffer.writeUInt32LE(value, offset),
    'uint32_t': (value, buffer, offset) => buffer.writeUInt32LE(value, offset),
    'int64_t': (value, buffer, offset) => buffer.writeBigInt64LE(value, offset),
    'uint64_t': (value, buffer, offset) => buffer.writeBigUInt64LE(value, offset),
    'float': (value, buffer, offset) => buffer.writeFloatLE(value, offset),
    'double': (value, buffer, offset) => buffer.writeDoubleLE(value, offset),
```    

You can see the referenced issue is still present.

It appears `tsc` was not run before publishing to npm

**Comment by padcom** [comment]
Hey! You're right! That was a super old version of the build! Thanks for spotting that.

1.0.3 released.

I'd be thankful if you followed up on that change and said if everything is working for you.

**Comment by padcom** [comment]
@gribbet As a side note the mavlink-mappings package has been updated to version 1.0.1-20210915. This is out of the semver schema so you'll probably have to update the version manually in package.json

**Comment by padcom** [comment]
That versioning is a bit tricky because the upstream XML definitions don't have a discrete versioning scheme, so I've had to improvise :)

**Comment by gribbet** [comment]
@padcom The issue is fixed in 1.0.3.
Thank you, thank you!

**Pull request merged**
